#!/usr/bin/env python3

# randomly selects an image from a folder

import os
import random
import sys

# color codes cuz i like colors
RED = "\u001b[0;31m"
GRN = "\u001b[0;32m"
BLU = "\u001b[0;34m"
RESET = "\u001b[0m"

ERROR = f"{RED}error{RESET}:"
NOTE = f"{BLU}note{RESET}:"

def list(path):
    image_exts = ( ".jpg", ".jpeg", ".png", ".bmp", ".ppm" )
    
    images = []
    
    for fn in os.listdir(path):
        if fn.lower().endswith(image_exts):
            images.append(fn)
    
    return images

def usage():
    print(f"{ERROR} no folder provided")
    print(f"{GRN}usage{RESET}: {sys.argv[0]} [folder]")
    print(f"{NOTE} folder should contain images ONLY")
    exit()

def main():
    argc = len(sys.argv)
    if argc == 1: usage()
    
    folder = sys.argv[1]
    
    files = list(folder)
    print(f"{os.path.join(folder, files[random.randrange(0,len(files))])}")

if __name__ == "__main__":
    main()

